const ulEl = document.querySelector('ul#categories');
console.log('Категории:', ulEl);
const childEl = ulEl.children;
console.log(`В списке  ${childEl.length} категории`);
const firstElChild = ulEl.firstElementChild;
const firstTitleEl = firstElChild.firstElementChild;
const firstUlChild = firstElChild.lastElementChild.children;
console.log(`Категория: ${firstTitleEl.textContent}`);
console.log(` Количество элементов: ${firstUlChild.length}`);
const secondElChild = childEl[1];
const secondTitleEl = childEl[1].firstElementChild;
const secondUlChild = secondElChild.lastElementChild.children;
console.log(`Категория: ${secondTitleEl.textContent}`);
console.log(` Количество элементов: ${secondUlChild.length}`);
const thirdElChild = childEl[2];
const thirdTitleEl = childEl[2].firstElementChild;
const thirdUlChild = thirdElChild.lastElementChild.children;
console.log(`Категория: ${thirdTitleEl.textContent}`);
console.log(`Количество элементов: ${thirdUlChild.length}`);